<?php

require_once '\..\source\controls\base\Task.php';

/**
 * Test class for Task.
 * Generated by PHPUnit on 2011-05-06 at 12:20:39.
 */
class TaskTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var Task
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Task;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	public function testIDonCreation()
	{
		$this->assertEquals($this->object->getID(), -1);
	}

	public function testIDSetGet() {
		$newId = 5;
		$this->object->setID($newId);
		$this->assertEquals($this->object->getID(), $newId);
	}

	public function testIDsetException()
	{
		$gotException = false;
		try {
			$this->object->setID(-1);
		} catch (Exception $e) {
			$gotException = true;
		}
		$this->assertTrue($gotException);
	}
	
	public function testAssignmentRefOnCreation()
	{
		$this->assertEquals($this->object->getAssignmentRef(), NULL);
	}

	public function testAssignmentRefSetGet() {
		$newId = 5;
		$this->object->setAssignmentRef($newId);
		$this->assertEquals($this->object->getAssignmentRef(), $newId);
	}

	public function testAssignmentRefsetException()
	{
		$gotException = false;
		try {
			$this->object->setAssignmentRef(-1);
		} catch (Exception $e) {
			$gotException = true;
		}
		$this->assertTrue($gotException);
	}
	
	public function testUserRefOnCreation()
	{
		$this->assertEquals($this->object->getUserRef(), NULL);
	}

	public function testUserRefSetGet() {
		$newId = 5;
		$this->object->setUserRef($newId);
		$this->assertEquals($this->object->getUserRef(), $newId);
	}

	public function testUserRefsetException()
	{
		$gotException = false;
		try {
			$this->object->setUserRef(-1);
		} catch (Exception $e) {
			$gotException = true;
		}
		$this->assertTrue($gotException);
	}

	public function testNameOnCreation()
	{
		$this->assertEquals($this->object->getName(), NULL);
	}

	public function testNameGetSet()
	{
		$name = "New Name";
		$this->object->setName($name);
		$this->assertEquals($this->object->getName(), $name);		
	}
	
	public function testNameSetExceptions() {
		$gotException = false;
		try {
			$this->object->setName(NULL);
		} catch (Exception $e) {
			$gotException = true;
		}
		$this->assertTrue($gotException);
		
		$gotException = false;
		try {
			$this->object->setName("");
		} catch (Exception $e) {
			$gotException = true;
		}
		$this->assertTrue($gotException);
	}

	public function testDescriptionOnCreation()
	{
		$this->assertEquals($this->object->getDescription(), NULL);
	}
	
	public function testDescriptionGetSet()
	{
		$desc = "My Description";
		$this->object->setDescription($desc);
		$this->assertEquals($this->object->getDescription(), $desc);
		
		$this->object->setDescription(NULL);
		$this->assertEquals($this->object->getDescription(), NULL);
	}

	public function testStarttimeOnCreation()
	{
		$this->assertEquals($this->object->getStarttime(), NULL);
	}

	public function testStartDateSetGet() {
		$date = new DateTime;
		$this->object->setStarttime($date);
		$this->assertEquals($this->object->getStarttime(), $date);
	}
	
	public function testEndtimeOnCreation()
	{
		$this->assertEquals($this->object->getEndtime(), NULL);
	}

	public function testEndtimeSetGet() {
		$date = new DateTime;
		$this->object->setEndtime($date);
		$this->assertEquals($this->object->getEndtime(), $date);
	}
	
	public function testStatusOnCreation()
	{
		$this->assertEquals($this->object->getStatus(), NULL);
	}

	public function testStatusGetSet()
	{
		$this->object->setStatus("Done");
		$this->assertEquals($this->object->getStatus(), "Done");
		
		$this->object->setStatus("PLAnned");
		$this->assertEquals($this->object->getStatus(), "Planned");
		
		$this->object->setStatus("in ProgresS");
		$this->assertEquals($this->object->getStatus(), "In Progress");
		
		$this->object->setStatus("cANCELED");
		$this->assertEquals($this->object->getStatus(), "Canceled");
	}
	
	public function testStatusExceptionOnSet()
	{
		$gotException = false;
		try {
			$this->object->setStatus("");
		} catch (Exception $e) {
			$gotException = true;
		}
		$this->assertTrue($gotException);
		
		$gotException = false;
		try {
			$this->object->setStatus("RANDOM string here");
		} catch (Exception $e) {
			$gotException = true;
		}
		$this->assertTrue($gotException);
		
		$gotException = false;
		try {
			$this->object->setStatus(NULL);
		} catch (Exception $e) {
			$gotException = true;
		}
		$this->assertTrue($gotException);
	}
}
?>
